logging:
  level:
    shop.daijian: debug
swagger:
  authorization:
    key-name: Authorization
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      db-type: mysql
aliyun:
  access-key-id: LTAI4FkPdbdceaJ7Vis1otsu
  access-key-secret: iN52f92vsOZFhO6QTdauCb9BVMTtd3
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket: daijian-server
    root-url: http://daijian-server.oss-cn-beijing.aliyuncs.com/
    base-dir: daijian/
---
# 生产环境
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql:3306/daijian?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: daijian
  redis:
    host: redis
    password: daijian
server:
  port: 8080
---
# 本地环境
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/daijian?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: daijian
  redis:
    host: localhost
    password: daijian
server:
  port: 8092